package convert_suhu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class app extends javax.swing.JFrame {

    /**
     * Creates new form app
     */
    public app() {
        initComponents();
        reset();
        
    }
    void reset(){
        tSuhuasal.setText(null);
        Hasil.setText(null);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tSuhuasal = new javax.swing.JTextField();
        tSkalaasal = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        tskalatujuan = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        Hasil = new javax.swing.JLabel();
        tConvert = new javax.swing.JButton();
        tClose = new javax.swing.JButton();
        tReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("konversi Suhu");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suhu Asal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        tSuhuasal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSuhuasalActionPerformed(evt);
            }
        });

        tSkalaasal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CELCIUS", "KELVIN", "FAHRENHEIT" }));
        tSkalaasal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSkalaasalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tSuhuasal)
                    .addComponent(tSkalaasal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tSuhuasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tSkalaasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Konversikan Ke", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        tskalatujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CELCIUS", "KELVIN", "FAHRENHEIT" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tskalatujuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tskalatujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        Hasil.setBackground(new java.awt.Color(255, 255, 51));
        Hasil.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Hasil.setForeground(new java.awt.Color(204, 0, 51));
        Hasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hasil.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                HasilAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        tConvert.setBackground(new java.awt.Color(0, 204, 0));
        tConvert.setText("Convert");
        tConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tConvertActionPerformed(evt);
            }
        });

        tClose.setBackground(new java.awt.Color(255, 0, 0));
        tClose.setText("Close");
        tClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCloseActionPerformed(evt);
            }
        });

        tReset.setBackground(new java.awt.Color(255, 153, 51));
        tReset.setText("Reset");
        tReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tConvert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 152, Short.MAX_VALUE)
                        .addComponent(tReset)
                        .addGap(18, 18, 18)
                        .addComponent(tClose))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tConvert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tReset)
                    .addComponent(tClose))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tConvertActionPerformed
        // TODO add your handling code here:
        double suhuasal = Double.parseDouble(tSuhuasal.getText());
        String skalaasal = tSkalaasal.getSelectedItem().toString();
        String skalatujuan = tskalatujuan.getSelectedItem().toString();
        double hasil = 0;
        
        if(skalaasal.equals("CELCIUS")&& skalatujuan.equals("CELCIUS")){
          hasil = suhuasal;
        }else if (skalaasal.equals("CELCIUS") && skalatujuan.equals("KELVIN")){  
          hasil = suhuasal + 273.15;
        } else if (skalaasal.equals("CELCIUS") && skalatujuan.equals("FAHRENHEIT")){ 
            hasil = (suhuasal * 1.8) + 32;
        }else if (skalaasal.equals("KELVIN") && skalatujuan.equals("CELCIUS")){  
          hasil = suhuasal - 273.15;
        }else if(skalaasal.equals("KELVIN")&& skalatujuan.equals("KELVIN")){
          hasil = suhuasal;
        }else if (skalaasal.equals("CELCIUS") && skalatujuan.equals("FAHRENHEIT")){ 
           hasil = (suhuasal - 273.15) * 1.8 + 32;
        }else if(skalaasal.equals("FAHRENHEIT")&& skalatujuan.equals("FAHRENHEIT")){
          hasil = suhuasal;
        }else if (skalaasal.equals("FAHRENHEIT") && skalatujuan.equals("CELCIUS")){  
          hasil = suhuasal - 32;
        }else if(skalaasal.equals("FAHRENHEIT")&& skalatujuan.equals("KELVIN")){
          hasil = (suhuasal - 32) * 5/9 + 273.15;
        }
        
          
          
        String skala = skalatujuan.substring(0, 1);
        Hasil.setText(String.format("%.2f", hasil) + "\u00B0" + skala);
    }//GEN-LAST:event_tConvertActionPerformed

    private void tResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_tResetActionPerformed

    private void tSkalaasalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSkalaasalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSkalaasalActionPerformed

    private void tSuhuasalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSuhuasalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSuhuasalActionPerformed

    private void tCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_tCloseActionPerformed

    private void HasilAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_HasilAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_HasilAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton tClose;
    private javax.swing.JButton tConvert;
    private javax.swing.JButton tReset;
    private javax.swing.JComboBox<String> tSkalaasal;
    private javax.swing.JTextField tSuhuasal;
    private javax.swing.JComboBox<String> tskalatujuan;
    // End of variables declaration//GEN-END:variables
}
